version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"  # location of pyproject.toml
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "python"
        versions: ["<3.10"]  # Ignore older Python versions
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      include: "scope"

  # GitHub Actions workflow updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
