services:
  - type: web
    name: AloneMusic Bot
    env: python
    plan: free
    region: oregon
    buildCommand: |
      pip install --upgrade pip
      pip install ".[all]"
    startCommand: python3 -m AloneMusic
    autoDeploy: true
    envVars:
      - key: API_ID
        fromDatabase: false
        value: ""
      - key: API_HASH
        fromDatabase: false
        value: ""
      - key: BOT_TOKEN
        fromDatabase: false
        value: ""
      - key: STRING_SESSION
        fromDatabase: false
        value: ""
      - key: MONGO_DB_URI
        fromDatabase: false
        value: ""
