name: Black

on: push

permissions:             # 👈 add this block
  contents: write        # needed to push code changes
  pull-requests: write   # needed to open PRs

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install black
        run: |
          python -m pip install --upgrade pip
          python -m pip install -U black

      - name: Run black
        run: black .

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "Formate By @TheAlonetean"
          title: "Format code."
          body: "Automated code formatting."
          labels: ⚫️ black
          branch: autofix
          delete-branch: true   # <-- ye add kar diya hai
          committer: TheAloneTeam <TheAloneTeam@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: true
